base_url = "https://placeviolette.net"
title = "place violette"
description = "a small, purple website"
default_language = "en"

compile_sass = true
minify_html = true
generate_feeds = true
build_search_index = false

[markdown]
smart_punctuation = false

[markdown.highlighting]
theme = "dracula"

[link_checker]
skip_anchor_prefixes = [
    "https://github.com/classabbyamp/mkinitcpio-tailscale/blob/master/README.md",
]

[extra]
buttons = [
    { url = "https://voidlinux.org", src = "/blog/void-button/void-button-anim.gif" },
    { url = "https://alyx.sh", src = "https://alyx.sh/images/88x31/alyxv2.png" },
]
